version: '3.8'
services:
  opensearch:
    image: opensearchproject/opensearch:3.3.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      # - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=HesloVesl0,fGs1
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -k -u admin:'HesloVesl0,fGs1' https://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s

  app:
    build: .
    container_name: opensearch-mcp-tests
    depends_on:
      opensearch:
        condition: service_healthy
    environment:
      - OPENSEARCH_URL=https://opensearch:9200
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=HesloVesl0,fGs1
      - OPENSEARCH_SSL_VERIFY=false
      - OPENSEARCH_MEMORY_CONTAINER_ID=lYaNPp0B5lgNGRI4mzj_
    #command: ["uv", "run", "pytest", "tests/", "-v"]
    stdin_open: true
    tty: true
    command: ["/bin/bash"]   # místo pytestu spustí bash